# Generated by Django 5.0.4 on 2024-04-29 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_car_name_remove_car_year_car_city_car_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 4, 7, 42, 731978, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
