# Generated by Django 5.0.4 on 2024-05-06 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_date_joined_carreview_userreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='numReviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 7, 39, 23, 993251, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
