# Generated by Django 5.0.4 on 2024-04-29 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_total_hours_booking_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 4, 31, 4, 87868, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
