# Generated by Django 5.0.4 on 2024-05-06 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_car_numreviews_car_rating_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(default='car_images/default.jpg', upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 12, 23, 56, 571407, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
