# Generated by Django 5.0.4 on 2024-09-17 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_car_img_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 16, 38, 7, 10217, tzinfo=datetime.timezone.utc), verbose_name='date joined'),
        ),
    ]
